runs:
  name: 'Alert Manager'
  description: 'Create an issue when a new alert is created'
  using: composite
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.20.4'

    - run: go run ./main.go